language: php
php:
  - '7.0'

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - composer require satooshi/php-coveralls

script:
  - phpunit
